---

- name: enable websso repository
  command: subscription-manager repos --enable=rh-sso-7.2-for-rhel-7-server-rpms

- name: enable websso repository
  command: subscription-manager repos --enable=jb-eap-7.1-for-rhel-7-server-rpms


- name: install websso prereqs
  tags:
    - websso
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk.x86_64
    - firewalld
    - ipa-admintools
    - openldap-clients
    - openssl
    - httpd
    - mod_ssl

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install websso yum group
  tags:
    - websso
  yum: name="@rh-sso7" state=present

- name: create symlink to keep dbus happy
  file:
    src: /usr/libexec/dbus-1
    dest: /lib64/dbus-1
    state: link

- name: restart dbus service
  systemd:
    state: restarted
    name: dbus

- name: kinit
  shell: klist &>/dev/null || echo {{ ipa_admin_password }} | kinit admin@{{ ipa_realm }}
  changed_when: false

- name: Add service principals
  ipaservice: principal="HTTP/sso.{{ ipa_realm | lower }}@{{ ipa_realm }}"


- name: HTTPS certificate OpenSSL
  getcert:
    key_file: /etc/pki/tls/private/localhost.key
    certificate_file: /etc/pki/tls/certs/localhost.crt
    kerberos_principal: "HTTP/sso.{{ ipa_realm | lower }}@{{ ipa_realm }}"
    bits: 2048
    ca: IPA



#TODO change group on these to match apache
#    key_file: /etc/pki/tls/private/localhost.key
#    certificate_file: /etc/pki/tls/certs/localhost.crt


#HTTPD as reverse proxy

- name: set up apache proxy
  tags:
    - keycloak
  copy: src=websso-proxy.conf
        dest=/etc/httpd/conf.d/websso-proxy.conf
        owner=root group=root mode="u=rw,g=r,o=r"


- name: enable standalone-ha.xml
  lineinfile:
    path: /opt/rh/rh-sso7/service-environment
    line: WILDFLY_SERVER_CONFIG=standalone-ha.xml


- name: rh_sso systemd services
  tags:
    - websso
  service: name={{ item }}
           enabled=yes
           state=started
  with_items:
     - httpd
     - rh-sso7

- name: create websso master admin user
  tags:
    - websso
  command: >
    {{ rhsso_dir }}/bin/add-user-keycloak.sh
    -r master
    -u {{ websso_master_admin_username }}
    -p {{ websso_master_admin_password }}
  register: add_user_result
  failed_when: not ( add_user_result.rc == 0 or "already added" in add_user_result.stderr )
  changed_when: add_user_result.rc == 0
  notify: restart websso

- name: enable firewalld
  tags:
    - websso
  service: enabled=yes
           state=started
           name=firewalld

- name: Open Firewall for services
  tags:
    - websso
  firewalld: port={{ item }}/tcp
             permanent=true
             state=enabled
             immediate=yes
  with_items: "{{ websso_firewall_ports  }}"



