---

- name: enable websso repository
  command: subscription-manager repos --enable=rh-sso-7.2-for-rhel-7-server-rpms

- name: install websso prereqs
  tags:
    - websso
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk.x86_64
    - firewalld
    - ipa-admintools
    - openldap-clients
    - openssl
    - httpd

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install websso yum group
  tags:
    - websso
  yum: name="@rh-sso7" state=present

- name: create symlink to keep dbus happy
  file:
    src: /usr/libexec/dbus-1
    dest: /lib64/dbus-1
    state: link

- name: restart dbus service
  systemd:
    state: restarted
    name: dbus

- name: kinit
  shell: klist &>/dev/null || echo {{ ipa_admin_password }} | kinit admin@{{ ipa_realm }}
  changed_when: false

- name: Add service principals
  ipaservice: principal="HTTP/sso.{{ ipa_realm | lower }}@{{ ipa_realm }}"

- name: HTTPS certificate
  getcert:
    location: /etc/httpd/alias
    nickname: Server-Cert    
    token: NSS Certificate DB
    pinfile: /etc/httpd/alias/pwdfile.txt
    kerberos_principal: "HTTP/sso.{{ ipa_realm | lower }}"
    bits: 2048
    ca: IPA


#HTTPD as reverse proxy

- name: set up apache proxy
  tags:
    - keycloak
  copy: src=websso-proxy.conf
        dest=/etc/httpd/conf.d/websso-proxy.conf
        owner=root group=root mode="u=rw,g=r,o=r"

- name: rh_sso systemd services
  tags:
    - websso
  service: name={{ item }}
           enabled=yes
           state=started
  with_items:
     - httpd
     - rh-sso7

- name: create websso master admin user
  tags:
    - websso
  command: >
    {{ rhsso_dir }}/bin/add-user-keycloak.sh
    -r master
    -u {{ websso_master_admin_username }}
    -p {{ websso_master_admin_password }}
  register: add_user_result
  failed_when: not ( add_user_result.rc == 0 or "already added" in add_user_result.stderr )
  changed_when: add_user_result.rc == 0
  notify: restart websso

- name: enable firewalld
  tags:
    - websso
  service: enabled=yes
           state=started
           name=firewalld

- name: Open Firewall for services
  tags:
    - websso
  firewalld: port={{ item }}/tcp
             permanent=true
             state=enabled
             immediate=yes
  with_items: "{{ websso_firewall_ports  }}"


- name: enable bind address
  lineinfile:
    dest: /etc/opt/rh/rh-sso7/keycloak/rh-sso7.conf
    line: WILDFLY_BIND="0.0.0.0"
    insertafter: ^#WILDFLY_BIND=0.0.0.0$
  notify:
     - restart websso

- name: realm in standalone.xml
  xml:
    path: /etc/opt/rh/rh-sso7/keycloak/standalone/standalone.xml
    xpath: /t:server/management/security-realms
    namespaces:
      t: urn:jboss:domain:5.0
    state: present
