---

- name: enable only OpenShift Repos
  tags:
    - oce-master
  shell: subscription-manager repos --enable="rhel-7-server-ose-3.7-rpms" 


- yum:
    name: "{{ item }}"
  with_items:
    - openshift-ansible
    - openshift-ansible-playbooks
    