---
- name: stop vm
  virt:
      name: "{{ item.name }}"
      uri:  qemu:///session
      state: destroyed
  with_items: "{{ cluster_hosts }}"
  ignore_errors: yes

- name: delete vm
  virt:
      name: "{{ item.name }}"
      command: undefine
      uri:  qemu:///session
  with_items: "{{ cluster_hosts }}"
  ignore_errors: yes

- name: remove VM backing store
  file:
    path: "{{ target_image_dir }}/{{ item.name }}.qcow2"
    state: absent
  with_items: "{{ cluster_hosts }}"

- name: destroy macvtap networks
  virt_net:
    command: destroy
    name: "macvtap-{{ item.cluster_host }}-{{ item.device }}"
  with_items: "{{ macvtap_networks }}"
  ignore_errors: yes


- name: undefine macvtap networks
  virt_net:
    command: undefine
    name: "macvtap-{{ item.cluster_host }}-{{ item.device }}"
  with_items: "{{ macvtap_networks }}"
  ignore_errors: yes

