
- hosts: identity
  remote_user: "{{ cloud_user }}"
  tags: all
  tasks: []

- hosts: identity
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - ipa
  roles:
    - common
    - ipaserver
#    - ipsilonserver
  vars:
    hostname: "{{ ansible_fqdn }}"
    ipa_admin_password: "{{ ipa_admin_user_password }}"
