
- hosts: ipa
  remote_user: "{{ cloud_user }}"
  tags: all
  tasks: []

- hosts: openstack
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - openstack
  roles:
    - common
    - { role: staticnetwork, when: ipa_nova_join is defined }
    - ipaclient
    - packstack
    - { role: nova-ipa, when: ipa_nova_join is defined }
  vars:
    hostname: "{{ ansible_fqdn }}"
    dns_search: "{{ ipa_domain }}"
    ipa_admin_password: "{{ipa_admin_user_password }}"
