- hosts: ipa
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - ipa
  roles:
    - common
    - ipaserver
    - ipsilonserver
  vars:
    hostname: "{{ ansible_fqdn }}"
    ipa_admin_password: "{{ ipa_admin_user_password }}"
    ipa_dns_forwarder:  "{{ ipa_forwarder }}"

- hosts: openstack
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - openstack
  roles:
    - common
    - ipaclient
    - packstack
  vars:
    hostname: "{{ ansible_fqdn }}"
    dns_search: "{{ ipa_domain }}"
    dns_nameservers:
      - "{{ nameserver }}"
    ipa_admin_password: "{{ipa_admin_user_password }}"
