- hosts: all
  connection: paramiko
  remote_user: "{{ cloud_user }}"
  tasks:
    - name: tty-less sudo
      sudo: yes
      lineinfile: dest=/etc/sudoers
                  state=absent
                  regexp='^Defaults(\s+)requiretty(\s*)$'
                  validate='visudo -cf %s'

- hosts: ipa
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - ipa
  roles:
    - common
    - ipaserver
    - ipsilonserver
  vars:
    hostname: "{{ ansible_fqdn }}"
    ipa_admin_password: "{{ ipa_admin_user_password }}"

- hosts: satellite
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - satellite
  roles:
    - common
    - ipaclient
    - satelliteserver
  vars:
    hostname: "{{ ansible_fqdn }}"
    dns_search: "{{ ipa_domain }}"
    ipa_admin_password: "{{ipa_admin_user_password }}"

- hosts: openstack
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - openstack
  roles:
    - common
    - ipaclient
    - packstack
  vars:
    hostname: "{{ ansible_fqdn }}"
    dns_search: "{{ ipa_domain }}"
    ipa_admin_password: "{{ipa_admin_user_password }}"
