- hosts: ipa
  sudo: yes
  remote_user: "{{ cloud_user }}"
  roles:
    - common
    - ipaserver
    - ipsilonserver
  vars:
    hostname: "{{ ansible_fqdn }}"
    #ipa_realm: Set By Inventory
    ipa_admin_password: "{{ ipa_admin_user_password }}"
    ipa_dns_forwarder:  "{{ ipa_forwarder }}"
    nightly_version: 20150717.n.4

- hosts: openstack
  sudo: yes
  remote_user: "{{ cloud_user }}"
  roles:
    - common
    - ipaclient
    - packstack
  vars:
    hostname: openstack.fedtest.org
    nightly_version: 20150717.n.4

    dns_search: "{{ ipa_domain }}" 
    dns_nameservers:
      - "{{ nameserver }}"

    #ipa_realm: Set By Inventory
    #ipa_domain: Set By Inventory
    ipa_admin_password: "{{ipa_admin_user_password }}"
