---
- name: int_network
  os_network:
    cloud: "{{ cloudname }}"
    state: present
    name: "{{ netname }}_network"
    external: false
  register: osnetwork

- os_subnet:
    cloud: "{{ cloudname }}"
    state: present
    network_name: "{{ netname }}_network"
    name: "{{ netname }}_subnet"
    cidr: 192.168.24.0/23
    dns_nameservers:
      - 8.8.8.7
      - 8.8.8.8

- os_router:
    cloud: "{{ cloudname }}"
    state: present
    name: "{{ netname }}_router"
    interfaces: "{{ netname }}_subnet"
    network: public

- os_security_group:
    cloud: "{{ cloudname }}"
    state: present
    name: "{{ securitygroupname }}"
    description: security group for foo servers

- os_security_group_rule:
    cloud: "{{ cloudname }}"
    security_group: "{{ securitygroupname }}"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

- name: create servers
  os_server:
    cloud: "{{ cloudname }}"
    state: present
    name: "{{ item }}.{{ clustername }}"

    image: rhel-guest-image-7.4-0
    key_name: ayoung-pubkey
    timeout: 200
    flavor: 2
    security_groups:
      - "{{ securitygroupname }}"
    nics:
      -  net-id:  "{{ osnetwork.network.id }}"
         net-name: "{{ netname }}_network" 
    meta:
      hostname: "{{ netname }}"
  with_items: "{{ cluster_hosts }}"
  register: osservers


- name: create CFME volume
  os_volume:
    cloud: "{{ cloudname }}"
    image: cfme-rhevm-5.9.0.15-1
    size: 80
    display_name: cfme_volume
  register: cfme_volume

- name: create CFME server
  os_server:
    cloud: "{{ cloudname }}"
    state: present
    name: "cfme.{{ clustername }}"
    key_name: ayoung-pubkey
    timeout: 200
    flavor: 2
    boot_volume: "{{ cfme_volume.volume.id }}"
    security_groups:
      - "{{ securitygroupname }}"
    nics:
      -  net-id:  "{{ osnetwork.network.id }}"
         net-name: "{{ netname }}_network"
    meta:
      hostname: "{{ netname }}"
  register: cfme_server

- name: create CFME database volume
  os_volume:
    cloud: "{{ cloudname }}"
    size: 80
    display_name: cfme_db_volume
  register: cfme_db_volume

- name: attach db volume to CFME
  os_server_volume:
    cloud: "{{ cloudname }}"
    state: present
    server: "cfme.{{ clustername }}"
    volume:  cfme_db_volume
    device: /dev/vdb

- file:
    path: "{{ config_dir }}"
    state: directory
    mode: 0755

- file:
    path: "{{ config_dir }}/deployments"
    state: directory
    mode: 0755

- file:
    path: "{{ cluster_dir }}"
    state: directory
    mode: 0755

- template:
    src: inventory.ini.j2
    dest: "{{ cluster_dir }}/inventory.ini"
    force: yes
    backup: yes