---

- os_server:
    cloud: "{{ cloudname }}"
    state: absent
    name: "cfme.{{ clustername }}"
  with_items: "{{ cluster_hosts  }}"

- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_volume
    state: absent
 
- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_db_volume
    state: absent

- os_server:
    cloud: "{{ cloudname }}"
    state: absent
    name: "{{ item }}.{{ clustername }}"
  with_items: "{{ cluster_hosts  }}"
    
- os_router:
    cloud: rdusalab
    state: absent
    name: "{{ netname }}_router"

- os_subnet:
    cloud: rdusalab
    state: absent
    network_name: "{{ netname }}_network"
    name: "{{ netname }}_subnet"

- os_network:
    cloud: rdusalab
    state: absent
    name: "{{ netname }}_network"
    external: false


