---

- name: Apache modules for SSSD
  tags:
    - ipsilon
  yum: name=mod_auth_mellon,ipsilon-client
       state=present

- name: enable apache identity modules
  tags:
    - ipsilon
  file: state=link
        src=/etc/httpd/conf.modules.d/{{ item }}.conf
        dest=/etc/httpd/conf.d/{{ item }}.conf
  with_items:
    - 10-auth_mellon
  notify:
    - restart httpd



- name: SAML2 config dirs
  tags:
    - ipsilon
  file: state=directory
        path=/etc/httpd/saml2/{{ item }}
  with_items:
    - ecp
    - websso

- name: Install Ipsilon for WebSSO
  tags:
    - ipsilon
  shell: >
    echo {{ ipa_admin_user_password }} | ipsilon-client-install
    --saml
    --saml-no-httpd
    --saml-base /v3/auth/OS-FEDERATION/websso/saml2
    --saml-sp /v3/auth/OS-FEDERATION/websso/saml2
    --saml-idp-url https://ipa.{{ ipa_domain }}/idp
    --saml-sp-logout /v3/auth/OS-FEDERATION/websso/saml2/logout
    --saml-sp-post /v3/auth/OS-FEDERATION/websso/saml2/postResponse
    --saml-sp-name openstackwebsso
    --saml-auth /v3/auth/OS-FEDERATION/websso/saml2
    --admin-user admin
    --admin-password -
    --port 5000
  args:
    creates: /etc/httpd/saml2/websso/metadata.xml
    chdir: /etc/httpd/saml2/websso/
  environment:
    # NOTE(jamielennox): This is ignored for now but should be used in place of
    # the echo above as soon as >1.0 comes out. That means can switch back to command instead of shell.
    IPSILON_ADMIN_PASSWORD: "{{ ipa_admin_user_password }}"
  notify:
    - restart httpd

- name: Create metadata key/cert
  tags:
    - ipsilon
  command: >
    openssl req
    -x509
    -batch
    -days 1825
    -newkey rsa:2048
    -nodes
    -subj "/CN=openstack.{{ ipa_domain }}"
    -keyout "/etc/httpd/saml2/ecp/metadata.key"
    -out "/etc/httpd/saml2/ecp/metadata.cert"
  args:
    creates: /etc/httpd/saml2/ecp/metadata.key
  notify:
    - restart httpd

- name: Copy metadata config generator
  tags:
    - ipsilon
  template: src=metadata-config.py.j2
            dest=/etc/httpd/saml2/ecp/metadata-config.py

- name: Create metadata file
  tags:
    - ipsilon
  shell: >
    make_metadata.py -x `which xmlsec1` metadata-config.py > /etc/httpd/saml2/ecp/metadata.xml
  args:
    creates: /etc/httpd/saml2/ecp/metadata.xml
    chdir: /etc/httpd/saml2/ecp/
  notify:
    - restart httpd

- name: Register ecp endpoint with ipsilon
  tags:
    - ipsilon
    - test1
  ipsilonprovider: username=admin
                   password={{ ipa_admin_user_password }}
                   name=openstackecp
                   metadata=/etc/httpd/saml2/ecp/metadata.xml
                   url=https://ipa.{{ ipa_domain }}/idp
                   link=https://openstack.{{ ipa_domain }}:5000/v3/OS-FEDERATION/identity_providers/ipsilon/protocols/saml2/auth

- name: Download IDP metadata
  tags:
    - ipsilon
  get_url: url=https://ipa.{{ ipa_domain }}/idp/saml2/metadata
           dest=/etc/httpd/saml2/idp-metadata.xml
  notify:
    - restart httpd

- name: SAML2 config dirs
  tags:
    - ipsilon
    - test1
  file: state=directory
        path=/etc/httpd/saml2/
        owner=apache
        mode=u=rwX,g=rX,o=
        recurse=yes
  with_items:
    - ecp
    - websso

- name: list idps
  command: openstack identity provider list -c ID -f csv
  environment: os_env
  register: os_idps
  changed_when: false

- name: list mappings
  command: openstack mapping list -c ID -f csv
  environment: os_env
  register: os_mappings
  changed_when: false


- name: copy rules file
  copy: src=mapping_ipsilon_saml2.json
        dest=/mapping_ipsilon_saml2.json

- name: Ipsilon identity provider
  command: >
    openstack identity provider create
    --remote-id https://ipa.{{ ipa_domain }}/idp/saml2/metadata
    ipsilon
  environment: os_env
  when: '"\"ipsilon\"" not in os_idps.stdout_lines'

- name: create Ipsilon mapping
  command: openstack mapping create --rules /mapping_ipsilon_saml2.json ipsilon_mapping
  environment: os_env
  when: ' "\"ipsilon_mapping\"" not in os_mappings.stdout_lines'

- name: list protocols Ipsilon
  command: openstack federation protocol list --identity-provider ipsilon -c id -f csv
  environment: os_env
  register: os_ipsilon_protocols
  changed_when: false

- name: federation protocol create
  command: >
    openstack federation protocol create
    --identity-provider ipsilon
    --mapping ipsilon_mapping
    saml2
  environment: os_env
  when: ' "\"saml2\"" not in os_ipsilon_protocols.stdout_lines'

- name: copy apache config files for port 80
  copy: src={{ item }}
        dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - 11-keystone_wsgi_admin.conf
    - 11-keystone_wsgi_main.conf
    - 12-keystone-federation.conf
  notify:
    - restart httpd

 

