---
cinder_password: cinder
cinder_db_password: cinder

glance_password: glance
glance_db_password: glance

admin_token: ADMIN
keystone_db_password: keystone

nova_password: nova
nova_db_password: nova

neutron_password: neutron
neutron_db_password: neutron

keystone_admin_password: password
keystone_demo_password: password

ssl_certs_dir: /etc/httpd/conf
ssl_cert: "{{ ssl_certs_dir }}/server.crt"
ssl_key: "{{ ssl_certs_dir }}/server.key"

haproxy_certs: /etc/haproxy/cert.pem

keytab: /etc/httpd/conf/openstack.keytab

packstack_dir: /packstack
