---

- os_server_facts:
    cloud: "{{ cloudname }}"
    server: "cfme.{{ clustername }}"
  register: cfme_server

- lineinfile:
    path: "{{ ssh_config_path }}"
    line:  "  Hostname {{ item.interface_ip  }}"
    state: absent
  with_items: "{{ cfme_server.ansible_facts.openstack_servers }}"

- lineinfile:
    path: "{{ ssh_config_path }}"
    line: Host "cfme.{{ clustername }}"
    state: absent

- os_server:
    cloud: "{{ cloudname }}"
    state: absent
    name: "cfme.{{ clustername }}"

- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_volume
    state: absent

- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_db_volume
    state: absent
