---


- name: restart httpd
  sudo: yes
  service: name=httpd state=restarted

- name: restart sssd
  service: name=sssd state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted
