---

- os_server_facts:
    cloud: "{{ cloudname }}"
    server: "{{ item.name }}.{{ clustername }}"
  with_items: "{{ cluster_hosts  }}"
  register: os_servers

- debug:
    var:  os_servers

- os_server_facts:
    cloud: "{{ cloudname }}"
    server: "cfme.{{ clustername }}"
  register: cfme_server

- os_server:
    cloud: "{{ cloudname }}"
    state: absent
    name: "cfme.{{ clustername }}"

- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_volume
    state: absent

- os_volume:
    cloud: "{{ cloudname }}"
    display_name: cfme_db_volume
    state: absent

- os_server:
    cloud: "{{ cloudname }}"
    state: absent
    name: "{{ item.name }}.{{ clustername }}"
  with_items: "{{ cluster_hosts  }}"

- os_volume:
    cloud: "{{ cloudname }}"
    display_name:  "{{ item.volume_name }}"
    state: absent
  with_items: "{{ cluster_volumes }}"
