# This is essentially a hit list of bad openstack decisions that should be fixed
---
- name: remove old cinder to glance link
  ini_file: dest=/etc/cinder/cinder.conf
            section=DEFAULT
            option=glance_host
            state=absent
  notify:
    - restart cinder-api  # i'm not sure this is required
    - restart cinder-volume

- name: name add cinder to glance link
  ini_file: dest=/etc/cinder/cinder.conf
            section=DEFAULT
            option=glance_api_servers
            state=present
            value=https://{{ hostname }}:9292
  notify:
    - restart cinder-api  # i'm not sure this is required
    - restart cinder-volume

- name: Fix nova novnc host
  ini_file: dest=/etc/nova/nova.conf
            section=DEFAULT
            option=novncproxy_base_url
            value=https://{{ hostname }}:6080/vnc_auto.html
  notify:
    - restart nova-api
    - restart nova-novncproxy
    - restart nova-scheduler

- name: Fix nova neutron url
  ini_file: dest=/etc/nova/nova.conf
            section=neutron
            option=url
            value=https://{{ hostname }}:9696
  notify:
    - restart nova-api
    - restart nova-novncproxy
    - restart nova-scheduler

- name: Fix nova glance url
  ini_file: dest=/etc/nova/nova.conf
            section=glance
            option=api_servers
            value=https://{{ hostname }}:9292
  notify:
    - restart nova-api
    - restart nova-novncproxy
    - restart nova-scheduler

- name: Fix neutron nova url
  ini_file: dest=/etc/neutron/neutron.conf
            section=DEFAULT
            option=nova_url
            value=https://{{ hostname }}:8774/v2
  notify:
    - restart neutron-api

- name: Fix neutron metadata auth
  ini_file: dest=/etc/neutron/metadata_agent.ini
            section=DEFAULT
            option=auth_url
            value=https://{{ hostname }}:5000/v2.0
  notify:
    - restart neutron-metadata

- name: Fix neutron metadata nova url
  ini_file: dest=/etc/neutron/metadata_agent.ini
            section=DEFAULT
            option={{ item.key }}
            value={{ item.value }}
  with_dict:
    nova_metadata_ip: "{{ hostname }}"
    nova_metadata_protocol: https
  notify:
    - restart neutron-metadata
