---
- name: add test file to federation
  copy: src=test
        dest=/var/www/cgi-bin/keystone/test
  notify:
    - restart httpd

- name: Apache modules for SSSD
  tags:
    - ipsilon
  yum: name=mod_auth_gssapi,mod_lookup_identity,mod_auth_mellon,ipsilon-client
       state=present

- name: Fix mod_lookup_identity conf file
  copy: src=55-lookup_identity.conf
        dest=/etc/httpd/conf.modules.d/55-lookup_identity.conf

- name: enable apache identity modules
  tags:
    - ipsilon
  file: state=link
        src=/etc/httpd/conf.modules.d/{{ item }}.conf
        dest=/etc/httpd/conf.d/{{ item }}.conf
  with_items:
#    - 10-auth_mellon
#    - 10-auth_gssapi
    - 55-lookup_identity
  notify:
    - restart httpd

- name: Apache common config files
  tags:
    - ipsilon
  template: src={{ item }}.j2
            dest=/etc/httpd/conf/{{ item }}
  with_items:
    - keystone-federation.conf
    - keystone-ssl.conf
  notify:
    - restart httpd

- name: Keystone main conf
  tags:
    - ipsilon
  template: src={{ item }}.j2
            dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - 10-keystone_wsgi_main.conf
    - 10-keystone_wsgi_admin.conf
  notify:
    - restart httpd


- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=auth
            option={{ item.key }}
            value={{ item.value }}
  with_dict:
    methods: external,password,token,saml2,kerberos
    kerberos: keystone.auth.plugins.mapped.Mapped
    saml2: keystone.auth.plugins.mapped.Mapped
  notify:
    - restart httpd

- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=federation
            option={{ item.key }}
            value={{ item.value }}
  with_dict:
    trusted_dashboard: https://{{ ansible_fqdn }}/dashboard/auth/websso/
    sso_callback_template: /etc/keystone/sso_callback_template.html
    remote_id_attribute: MELLON_IDP
  notify:
    - restart httpd

- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=kerberos
            option=remote_id_attribute
            value=IDP_ID
  notify:
    - restart httpd

- name: update keystone endpoints - public
  command: mysql -vv -u root keystone -e "update endpoint set url=\"https://{{ hostname }}:5000/v2.0\" where url like \"http://%:5000/v2.0\";"
  register: keystonesqlpublic
  changed_when: '"0 rows affected" not in keystonesqlpublic.stdout'

- name: update keystone endpoints - admin
  command: mysql -vv -u root keystone -e "update endpoint set url=\"https://{{ hostname }}:35357/v2.0\" where url like \"http://%:35357/v2.0\";"
  register: keystonesqladmin
  changed_when: '"0 rows affected" not in keystonesqladmin.stdout'
