---
- name: copy rules file
  template: src=mapping_sssd.json.j2
            dest=/mapping_sssd.json

- name: SSSD identity provider
  command: openstack identity provider create --remote-id SSSD   sssd
  environment: os_env
  when: '"\"sssd\"" not in os_idps.stdout_lines'

- name: create SSSD mapping
  command: openstack mapping create --rules /mapping_sssd.json kerberos_mapping
  environment: os_env
  when: ' "\"kerberos_mapping\"" not in os_mappings.stdout_lines'

- name: list protocols SSSD
  command: openstack federation protocol list --identity-provider sssd -c id -f csv
  environment: os_env
  register: os_sssd_protocols
  changed_when: false

- name: federation SSSD protocol create
  command: >
    openstack federation protocol create
    --identity-provider sssd
    --mapping kerberos_mapping
    kerberos
  environment: os_env
  when: ' "\"kerberos\"" not in os_sssd_protocols.stdout_lines'
