---
- name: add test file to federation
  copy: src=test
        dest=/var/www/cgi-bin/keystone/test
  notify:
    - restart httpd

- name: Apache modules for SSSD
  yum: name=mod_auth_gssapi,mod_lookup_identity,mod_auth_mellon,ipsilon-client
       state=present

- name: Fix mod_lookup_identity conf file
  copy: src=55-lookup_identity.conf
        dest=/etc/httpd/conf.modules.d/55-lookup_identity.conf

- name: enable apache identity modules
  file: state=link
        src=/etc/httpd/conf.modules.d/{{ item }}.conf
        dest=/etc/httpd/conf.d/{{ item }}.conf
  with_items:
    - 10-auth_mellon
    - 10-auth_gssapi
    - 55-lookup_identity
  notify:
    - restart httpd

- name: Apache common config files
  template: src={{ item }}.j2
            dest=/etc/httpd/conf/{{ item }}
  with_items:
    - keystone-federation.conf
    - keystone-ssl.conf
  notify:
    - restart httpd

- name: Keystone main conf
  template: src={{ item }}.j2
            dest=/etc/httpd/conf.d/{{ item }}
  with_items:
    - 10-keystone_wsgi_main.conf
    - 10-keystone_wsgi_admin.conf
  notify:
    - restart httpd

- name: SAML2 config dir
  file: state=directory
        path=/etc/httpd/saml2
        owner=apache
        mode=0750

- name: Install Ipsilon
  shell: >
    echo {{ ipa_admin_user_password }} | ipsilon-client-install
    --saml
    --saml-no-httpd
    --saml-base /v3/auth/OS-FEDERATION/websso/saml2
    --saml-sp /v3/auth/OS-FEDERATION/websso/saml2
    --saml-idp-url https://ipa.{{ ipa_domain }}/idp
    --saml-sp-logout /v3/auth/OS-FEDERATION/websso/saml2/logout
    --saml-sp-post /v3/auth/OS-FEDERATION/websso/saml2/postResponse
    --saml-sp-name openstack
    --saml-auth /v3/auth/OS-FEDERATION/websso/saml2
    --admin-user admin
    --admin-password -
    --port 5000
  args:
    creates: /etc/httpd/saml2/metadata.xml
    chdir: /etc/httpd/saml2/
  environment:
    # NOTE(jamielennox): This is ignored for now but should be used in place of
    # the echo above as soon as >1.0 comes out. That means can switch back to command instead of shell.
    IPSILON_ADMIN_PASSWORD: "{{ ipa_admin_user_password }}"
  notify:
    - restart httpd

- name: Download IDP metadata
  get_url: url=https://ipa.{{ ipa_domain }}/idp/saml2/metadata
           dest=/etc/httpd/saml2/idp-metadata.xml
  notify:
    - restart httpd

- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=auth
            option={{ item.key }}
            value={{ item.value }}
  with_dict:
    methods: external,password,token,saml2,kerberos
    kerberos: keystone.auth.plugins.mapped.Mapped
    saml2: keystone.auth.plugins.mapped.Mapped
  notify:
    - restart httpd

- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=federation
            option={{ item.key }}
            value={{ item.value }}
  with_dict:
    trusted_dashboard: https://{{ ansible_fqdn }}/dashboard/auth/websso/
    sso_callback_template: /etc/keystone/sso_callback_template.html
    remote_id_attribute: MELLON_IDP
  notify:
    - restart httpd

- name: Kerberos as Login mechanism
  ini_file: dest=/etc/keystone/keystone.conf
            section=kerberos
            option=remote_id_attribute
            value=IDP_ID
  notify:
    - restart httpd

- name: update keystone endpoints - public
  command: mysql -vv -u root keystone -e "update endpoint set url=\"https://{{ hostname }}:5000/v2.0\" where url like \"http://%:5000/v2.0\";"
  register: keystonesqlpublic
  changed_when: '"0 rows affected" not in keystonesqlpublic.stdout'

- name: update keystone endpoints - admin
  command: mysql -vv -u root keystone -e "update endpoint set url=\"https://{{ hostname }}:35357/v2.0\" where url like \"http://%:35357/v2.0\";"
  register: keystonesqladmin
  changed_when: '"0 rows affected" not in keystonesqladmin.stdout'
