---
- name: install hacks copr repo
  copy: src=jamielennox-rippowam-updates-epel-7.repo
        dest=/etc/yum.repos.d/jamielennox-rippowam-updates-epel-7.repo

- include: ipa-pre-packstack.yml

# # NOTE(jamielennox): are epel and pip needed anymore?
# - name: install epel
#   yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#        state=installed
#
# - name: install pip
#   yum: name=python-pip
#        state=installed
#
- include: packstack.yml
- include: serviceauth.yml

- name: install adminrc file
  template: src=adminrc.j2
            dest=~/adminrc

- name: install demorc file
  template: src=demorc.j2
            dest=~/demorc

- include: infopipe.yml
- include: keystone.yml
- include: horizon.yml
- include: ipa-post-packstack.yml
# - include: firewall.yml
- meta: flush_handlers
- include: keystone-environment.yml
- include: keystone-sssd.yml
- include: keystone-ipsilon.yml
