---
- name: Install rhos-release
  register: packstackrepo
  command: rpm -ivh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
  ignore_errors: yes

- name: Install repos
  register: packstackrepo
  command: rhos-release 8
  ignore_errors: yes

- include: ipa-pre-packstack.yml
- include: packstack.yml
- include: serviceauth.yml
- include: haproxy.yml
- include: haproxy-fixups.yml
- include: infopipe.yml
- include: keystone.yml
- include: horizon.yml
- include: ipa-post-packstack.yml
# - include: firewall.yml
- meta: flush_handlers
- include: keystone-environment.yml
- include: keystone-sssd.yml
#- include: test-encrypted-volumes.yml

- name: install accrc files
  sudo: no
  template: src={{ item }}.j2
            dest=~/{{ item }}
  with_items:
    - adminrc
    - demorc
    - kerb-accrc
    - fed-accrc



- name: get local copies of rc files
  sudo: no
  local_action: template src={{ item }}.j2
                      dest={{ deployment_dir  }}/{{ item }}
  with_items:
    - adminrc
    - demorc
    - kerb-accrc
    - fed-accrc
