---
- name: install hacks copr repo
  copy: src=jamielennox-rippowam-updates-epel-7.repo
        dest=/etc/yum.repos.d/jamielennox-rippowam-updates-epel-7.repo

- include: ipa-pre-packstack.yml
- include: packstack.yml
- include: serviceauth.yml
- include: infopipe.yml
- include: keystone.yml
- include: horizon.yml
- include: ipa-post-packstack.yml
# - include: firewall.yml
- meta: flush_handlers
- include: keystone-environment.yml
- include: keystone-sssd.yml
- include: keystone-ipsilon.yml
#- include: barbican.yml
#- include: test-encrypted-volumes.yml

- name: install accrc files
  sudo: no
  template: src={{ item }}.j2
            dest=~/{{ item }}
  with_items:
    - adminrc
    - demorc
    - kerb-accrc
