---
- name: upgrade to kerberized mariadb
  tags:
    - mariadb
  yum:  name=mariadb-galera-server
        state=latest

- name: kinit
  tags:
    - mariadb
  shell: klist &>/dev/null || echo {{ ipa_admin_password }} | kinit admin@{{ ipa_realm }}
  changed_when: false

- name: MySQL service
  tags:
    - mariadb
  ipaservice: principal={{ mysql_principal }}

- name: Get Keytab
  tags:
    - mariadb
  command:  >
    ipa-getkeytab
    -s ipa.{{ ipa_domain }}
    -k /var/lib/mysql/mysql.keytab
    -p "{{ mysql_principal }}"
  args:
    creates: /var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb

- name: kdestroy
  tags:
    - mariadb
  shell: kdestroy
  changed_when: false

- name: set keytab permissions
  tags:
    - mariadb
  file: owner=mysql
        group=mysql
        mode=0600
        path=/var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb


- name: install server.cnf
  tags:
    - mariadb
  template: src=server.cnf
            dest=/etc/my.cnf.d/server.cnf
  notify:
    - restart mariadb


