---

- name: Install packstack
  yum: name=openstack-packstack
       state=present
       update_cache=yes

- name: Copy answer file
  template: src=answers.txt.j2
            dest=/answers.txt
  register: answers
  when: not ipa_nova_join

- name: Copy answer file
  template: src=answers.txt.autoregister-neutron
            dest=/answers.txt
  register: answers
  when: ipa_nova_join

- name: Run packstack
  command: "packstack --answer-file /answers.txt"
  when: answers.changed
