---
- name: Install packstack repos
  register: packstackrepo
  copy: src=RH7-RHOS-7.0.repo
        dest=/etc/yum.repos.d/RH7-RHOS-7.0.repo

- name: Install packstack
  yum: name=openstack-packstack
       state=present
       update_cache=yes

- name: Copy answer file
  template: src=answers.txt.j2
            dest=/answers.txt
  register: answers

- name: Run packstack
  command: "packstack --answer-file /answers.txt"
  when: answers.changed
