---
- name: Install Ipsilon Packages
  yum: name=ipsilon,ipsilon-saml2,ipsilon-authgssapi,ipsilon-tools-ipa,ipsilon-infosssd
       state=present

- name: Install ipsilon server
  command: ipsilon-server-install --ipa=yes --gssapi=yes --form=yes --info-sssd=yes --admin-user=admin
  args:
    creates: /etc/ipsilon/idp/idp.conf
  notify: restart httpd

- name: Use NSS rather than SSL
  replace: regexp=SSLRequireSSL
           replace=NSSRequireSSL
           dest=/etc/httpd/conf.d/ipsilon-idp.conf
  notify: restart httpd

- name: Remove SSL conf file
  file: path=/etc/httpd/conf.d/ssl.conf
        state=absent
  notify: restart httpd

- name: Add ECP PAM file
  copy: src=ipsilon_ecp
        dest=/etc/pam.d/ipsilon_ecp

- name: Add ECP HTTPd conf file
  copy: src=ipsilon-idp-ecp.conf
        dest=/etc/httpd/conf.d/ipsilon-idp-ecp.conf
  notify: restart httpd
