---
- name: copy vm image
  copy:
    src:  "{{ source_image_dir }}/{{ source_image_file }}"
    dest: "{{ target_image_dir }}/{{ source_image_file }}"
    owner: qemu
    group: qemu
    mode: u=rw,g=r,o=r

- name: 
  copy: remote_src=True
    src="{{ target_image_dir }}/{{ source_image_file }}"
    dest="{{ target_image_dir }}//{{ item.name }}.qcow2"
  with_items: "{{ cluster_hosts }}"


- name: define vm
  virt:
      name: "{{ item.name }}"
      command: define
      xml: "{{ lookup('template', 'vm.xml.j2') }}"
      uri:  qemu:///session
  with_items: "{{ cluster_hosts }}"

- name: run vm
  virt:
      name: "{{ item.name }}"
      uri:  qemu:///session
      state: running
  with_items: "{{ cluster_hosts }}"


