


- name: login
  command:  az login --service-principal --username {{ name }}  --password  {{ password  }}  --tenant {{ tenant }}


- name: create resource group
  command:  az group create --name {{ az_resources }}  \
    --location {{ az_location }}


- name: Create virtual network
  command: az network vnet create \
    --resource-group {{ az_resources }} \
    --name "{{ az_network }}" \
    --address-prefix 192.168.0.0/16 \
    --subnet-name "{{ az_subnet }}" \
    --subnet-prefix 192.168.1.0/24


- name: Create a public IP address
  command: az network public-ip create \
    --resource-group {{ az_resources }} \
    --name "{{ item.name }}.publicip" \
    --dns-name {{ item.name }}ayoung
  with_items: "{{ cluster_hosts }}"

- name: Create a network security group
  command: az network nsg create \
   --resource-group {{ az_resources }} \
   --name "{{ az_sec_group }}"

- name: Allow SSH traffic
  command: az network nsg rule create \
    --resource-group {{ az_resources }} \
    --nsg-name "{{ az_sec_group }}" \
    --name "{{ az_sec_group }}SSH" \
    --protocol tcp \
    --priority 1000 \
    --destination-port-range 22 \
    --access allow

- name: Allow HTTP traffic
  command: az network nsg rule create \
    --resource-group {{ az_resources }} \
    --nsg-name "{{ az_sec_group }}" \
    --name "{{ az_sec_group }}HTTP" \
    --protocol tcp \
    --priority 1001 \
    --destination-port-range 80 \
    --access allow

- name: Allow HTTPS traffic
  command: az network nsg rule create \
    --resource-group {{ az_resources }} \
    --nsg-name "{{ az_sec_group }}" \
    --name "{{ az_sec_group }}HTTPS" \
    --protocol tcp \
    --priority 1002 \
    --destination-port-range 443 \
    --access allow

- name: Create a Virtual NIC
  command: az network nic create \
    --resource-group {{ az_resources }} \
    --name "{{ item.name }}.nic"
    --vnet-name "{{ az_network }}" \
    --subnet "{{ az_subnet }}" \
    --public-ip-address "{{ item.name }}.publicip" \
    --network-security-group "{{ az_sec_group }}"
  with_items: "{{ cluster_hosts }}"

- name: Create an availability set
  command: az vm availability-set create \
    --resource-group  {{ az_resources }} \
    --name {{ az_av_set }}

- name: create vm
  command: az vm create \
    -n {{ item.name }}  \
    -g {{ az_resources }} \
    --image RHEL  \
    --availability-set {{ az_av_set }} \
    --nics "{{ item.name }}.nic" \
    --admin-username cloud-user \
    --generate-ssh-keys
  with_items: "{{ cluster_hosts }}"
  register: osservers



- name: logout
  command:  az logout