---
- name: install kerberized mariadb repo
  tags:
    - mariadb
  copy: src=rharwood-mariadb-epel-7.repo
        dest=/etc/yum.repos.d/

- name: upgrade to kerberized mariadb
  yum:  name=mariadb-galera-debuginfo,mariadb-galera-server,ipa-admintools
        state=latest

- name: kinit
  tags:
    - mariadb
  shell: klist &>/dev/null || echo {{ ipa_admin_password }} | kinit admin@{{ ipa_realm }}
  changed_when: false

- name: MySQL service
  tags:
    - mariadb
  ipaservice: principal={{ mysql_principal }}

- name: Get Keytab
  tags:
    - mariadb
  command:  >
    ipa-getkeytab
    -s ipa.{{ ipa_domain }}
    -k /var/lib/mysql/mysql.keytab
    -p "{{ mysql_principal }}"
  args:
    creates: /var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb

- name: set keytab permissions
  tags:
    - mariadb
  file: owner=mysql
        group=mysql
        mode=0600
        path=/var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb

- name: check for kerberos module
  tags:
    - mariadb
  command: mysql keystone -u root  --execute="SHOW PLUGINS;"
  register: mysql_modules
  changed_when: false

- name: install kerberos module
  tags:
    - mariadb
  command: mysql keystone -u root --execute="INSTALL PLUGIN kerberos soname 'kerberos';"
  when: "'kerberos' not in mysql_modules.stdout"

- name: install server.cnf
  tags:
    - mariadb
  template: src=server.cnf
            dest=/etc/my.cnf.d/server.cnf
  notify:
    - restart mariadb

- name: kdestroy
  tags:
    - mariadb
  shell: kdestroy
  changed_when: false
