---
- name: install kerberized mariadb repo
  copy: src=rharwood-mariadb-epel-7.repo
        dest=/etc/yum.repos.d/

- name: upgrade to kerberized mariadb
  yum:  name=mariadb-galera-debuginfo,mariadb-galera-server,ipa-admintools
        state=latest

- name: kinit
  shell: klist &>/dev/null || echo {{ ipa_admin_password }} | kinit admin@{{ ipa_realm }}
  changed_when: false

- name: check for MySQL Service
  command:   >
    curl -s
    -H Referer:https://ipa.{{ ipa_domain }}/ipa
    -H "Content-Type:application/json"
    -H "Accept:applicaton/json"
    --negotiate -u ":"
    -d  '{"method":"service_show","params":[["{{ mysql_principal }}"],{}],"id":0}'
    -X POST https://ipa.{{ ipa_domain }}/ipa/json
  register: ipa_service_show_mysql_result

- name: add maria service
  command: >
    curl -s
    -H Referer:https://ipa.{{ ipa_domain }}/ipa
    -H "Content-Type:application/json"
    -H "Accept:applicaton/json"
    --negotiate -u ":"
    -d  '{"method":"service_add","params":[["{{ mysql_principal }}"],{}],"id":0}'
    -X POST https://ipa.{{ ipa_domain }}/ipa/json
  register: ipa_service_create_mysql_result

- name: Get Keytab
  command:  >
    ipa-getkeytab
    -s ipa.{{ ipa_domain }}
    -k /var/lib/mysql/mysql.keytab
    -p "{{ mysql_principal }}"
  args:
    creates: /var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb

- name: set keytab permissions
  file: owner=mysql
        group=mysql
        mode=0600
        path=/var/lib/mysql/mysql.keytab
  notify:
    - restart mariadb

- name: check for kerberos module
  command: mysql keystone -u root  --execute="SHOW PLUGINS;"
  register: mysql_modules
  changed: false

- name: install kerberos module
  command: mysql keystone -u root --execute="INSTALL PLUGIN kerberos soname 'kerberos';"
  when: "'kerberos' not in mysql_modules.stdout"

- name: install server.cnf
  template: src=server.cnf
            dest=/etc/my.cnf.d/server.cnf
  notify:
    - restart mariadb

- name: kdestroy
  shell: kdestroy
  changed: false
