---
- name: python-keystoneclient-kerberos
  yum: name=python-keystoneclient-kerberos
       state=installed

- name: nova v3 authentication
  ini_file: section=keystone_authtoken
            dest=/etc/nova/nova.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"

  notify:
    - restart nova-api

- name: glance-api v3 authentication
  ini_file: section=keystone_authtoken
            dest=/etc/glance/glance-api.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"
  notify:
    - restart glance-api

- name: glance-registry v3 authentication
  ini_file: section=keystone_authtoken
            dest=/etc/glance/glance-registry.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"
  notify:
    - restart glance-registry

- name: cinder v3 authentication
  ini_file: section=keystone_authtoken
            dest=/etc/cinder/cinder.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"
  notify:
    - restart cinder-api

- name: neutron v3 authentication
  ini_file: section=keystone_authtoken
            dest=/etc/neutron/neutron.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"
  notify:
    - restart neutron-api

- name: neutron v3 authentication continued
  ini_file: section=DEFAULT
            dest=/etc/neutron/neutron.conf
            option=nova_admin_auth_url
            value="https://{{ hostname }}:5000/v3"
  notify:
    - restart neutron-api

- name: nova/neutron v3 authentication
  ini_file: section=neutron
            dest=/etc/nova/nova.conf
            option={{ item.key }}
            value={{ item.value }}
  with_dict: "{{ service_authtoken }}"
  notify:
    - restart nova-compute

- name: remove nova v2 overrides
  ini_file: dest=/usr/share/nova/nova-dist.conf
            section=keystone_authtoken
            state=absent
  notify:
    - restart nova-api
