- hosts: ipa
  remote_user: "{{ cloud_user }}"
  tags: all
  tasks: []

- hosts: ipa
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - ipa
  roles:
    - subscribe
    - update
    - ipaserver

  vars:
    ipa_fqdn: "idm.awx.devstack"
    ipa_admin_password: "{{ ipa_admin_user_password }}"
