- hosts: overcloud-controller-0
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - openstack
  roles:
    - ipaclient
    - keyfed
  vars:
    hostname: "{{ ansible_fqdn }}"
    dns_search: "{{ ipa_domain }}"
    ipa_admin_password: "{{ipa_admin_user_password }}"
