
- hosts: masters
  remote_user: "{{ cloud_user }}"
  tags: all
  tasks: []

- hosts: masters, nodes, bastion
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags: ipaclient
  roles:
    - subscribe
    - ipaclient


- hosts: masters
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags: oce
  roles:
    - oce-master

