
- hosts: master
  remote_user: "{{ cloud_user }}"
  tags: all
  tasks: []

- hosts: master, nodes
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags: ipaclient
  roles:
    - subscribe
    - ipaclient


- hosts: master
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags: oce
  roles:
    - oce-master

