# To be run after the site.yml file.  Sets up a satellite server

- hosts: satellite
  sudo: yes
  remote_user: "{{ cloud_user }}"
  tags:
    - satellite
  roles:
    - subscribe
    - satelliteserver
