---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install ipa packages
  tags:
    - ipaserver
  yum: name={{ item }} state=present
  with_items:
    - ipa-server-dns
    - ipa-server
    - firewalld

# next two tasks are a workaround for
# https://bugzilla.redhat.com/show_bug.cgi?id=1519206
- name: create symlink to keep dbus happy
  file:
    src: /usr/libexec/dbus-1   
    dest: /lib64/dbus-1 
    state: link

- name: restart dbus service 
  systemd:
    state: restarted
    name: dbus



- name: Get default DNS
  resolver:
  register: dns_forwarder
  changed_when: false

- name: install ipa
  tags:
    - ipaserver
  command: >
    ipa-server-install -U
    --realm {{ ipa_realm }}
    --domain {{ ipa_realm | lower }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ dns_forwarder.nameservers[0] }}
  args:
    creates: /etc/ipa/ca.crt

- name: enable firewalld
  tags:
    - ipaserver
  service: enabled=yes
           state=started
           name=firewalld

- name: Open Firewall for services
  tags:
    - ipaserver
  firewalld: service={{ item }}
             permanent=true
             state=enabled
             immediate=yes
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - dns
    - kerberos
    - kpasswd
    - ntp

- name: Open Firewall for ports
  tags:
    - ipaserver
  firewalld: port={{ item }}
             permanent=true
             state=enabled
             immediate=yes
  with_items:
    - 9180/tcp
    - 9443-9446/tcp
    - 9701/tcp
    - 7389/tcp
    - 8443/tcp

- name: Fetch krb5config
  fetch: src=/etc/krb5.conf
         dest={{ inventory_dir }}/krb5.conf
         flat=yes

- name: Fetch cacert
  fetch: src=/etc/ipa/ca.crt
         dest={{ inventory_dir }}/ca.crt
         flat=yes

 