---
 # work around https://bugzilla.redhat.com/show_bug.cgi?id=1241941
 # add ipa-server above and remove this when fix lands in nightlys
 # in the current nightly python-cryptography is missing as well. It's in yesterday's though.
 #- name: create /iparepo
 #  file: dest=/iparepo
 #        state=directory
 #
 #- name: install createrepo
 #  yum: name=createrepo
 #       state=present
 #
 #- name: download hacked ipa
 #  get_url: url="{{ item }}"
 #           dest=/iparepo/{{ item | basename }}
 #  with_items:
 #    "{{ repo_urls }}"
 #  register: createrepo
 #
 #- name: createrepo file
 #  command: createrepo /iparepo
 #  when: createrepo.changed
 #
 #- name: add ipa repo to platform
 #  copy: dest=/etc/yum.repos.d/ipa.repo
 #        src=ipa.repo
 #
- name: install ipa packages
  yum: name={{ item }} state=present
  with_items:
    - bind-dyndb-ldap
    - bind-pkcs11
    - bind-pkcs11-utils
    - ipa-server
    - firewalld
    - ipa-server-dns

- name: install ipa
  command: >
    ipa-server-install -U
    --realm {{ ipa_realm }}
    --domain {{ ipa_realm | lower }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ ipa_dns_forwarder }}
  args:
    creates: /etc/ipa/ca.crt

- name: install ipa kra
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/httpd/alias/kra-agent.pem

- name: Open Firewall for services
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - dns
    - kerberos
    - kpasswd
    - ntp

- name: Open Firewall for ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 9180/tcp
    - 9443-9446/tcp
    - 9701/tcp
    - 7389/tcp
    - 8443/tcp
  notify: restart firewalld

